# @format

name: Django CI/CD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_DB: mydatabase
          POSTGRES_USER: mydatabaseuser
          POSTGRES_PASSWORD: mypassword
        options: >-
          --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
        ports:
          - 5432:5432

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
         #my code
          python -m venv venv
          source venv/bin/activate  # Linux/MacOS    
          pip install Django djangorestframework psycopg2-binary
          django-admin startproject myproject
          cd myproject
          python manage.py startapp myapp

      - name: Run migrations
        run: 
          python manage.py makemigrations
          python manage.py migrate

      - name: Run tests
        #mycode
        run:
          pip install pytest pytest-django black isort ruff
        
        run: pytest 
        
      - name: Format code
        run: |
          black .
          isort .
          ruff .

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@4.1.0
        with:
          branch: gh-pages
          folder: dist
